package pt.ipca.alunos.checklist
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class ChecklistViewModel(private val db: ChecklistDatabase) : ViewModel() {
    private val _items = MutableStateFlow<List<ItemEntity>>(emptyList())
    val items: StateFlow<List<ItemEntity>> = _items.asStateFlow()

    init {
        loadItems()
    }

    private fun loadItems() {
        viewModelScope.launch {
            db.itemDao().getAll().collect { itemList ->
                _items.value = itemList
            }
        }
    }

    fun addItem(name: String) {
        viewModelScope.launch {
            val item = ItemEntity(id = 0, name = name) // id=0, auto-generated by Room
            db.itemDao().insert(item)
            // No need to reload; Flow from getAll will update automatically
        }
    }

    fun deleteItem(item: ItemEntity) {
        viewModelScope.launch {
            db.itemDao().delete(item)
            // No need to reload; Flow from getAll will update automatically
        }
    }
}